# Generated by Django 3.2 on 2021-04-30 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_comment_shows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='category.category'),
        ),
    ]
