# Generated by Django 3.2 on 2021-04-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_tvshow_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='shows',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='category.tvshow'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='category.category'),
        ),
    ]
